### ISSUE TITLE
Improve documentation on rucio.cfg vs configuration table

### ISSUE THREAD

**Issue by dchristidis** [rucio/documentation#183]
![Screenshot from 2023-03-03 12-14-31](https://user-images.githubusercontent.com/2452306/222707412-b367a011-ad18-4bf3-9956-c142c5d55559.png)

**Comment by voetberg** [comment]
Clarification questions because I can't tell from reading the code: 
- Does the config file get loaded into the config table on initialization? (As the cache or as something else?) 
- Do updates using `client config ....` overwrite the config table or file or both? Or does this just impact the cache?

**Comment by bari12** [comment]
- `rucio.cfg` does not get loaded into the config table. There is just an order of precedence: If a configuration is set in the `rucio.cfg` this one is used, if not the config table is queried. 
- Only updates the table
